### ISSUE TITLE
块级格式化上下文

### ISSUE THREAD

**Issue by askwuxue** [askwuxue/askwuxue.github.io#20]
---
title: 块级格式化上下文
date: 2018-04-17 13:41:10
tags: CSS
categories: CSS
---
#### 格式化上下文

_在解决外边距叠加的时候，MDN给出了这个概念，触发 了BFC不会发生外边距叠加，今天来看一下，理解不是特别深刻，今天通过查阅资料，解决这个问题。_

**MDN的定义**

块级格式化上下文（Block Formatting Context，BFC） 是Web页面的可视化CSS渲染的一部分，是布局过程中生成块级盒子的区域，也是浮动元素与其他元素的交互限定区域。

看了几个文档都没有太看明白，借鉴：前端精选文摘-BFC背后的原理一文，基本上为我们解释清楚了，我决定，结合自己的理解与大佬的文章巩固一下。

##### 前置知识

**开始之前，需要了解下面三点。**
1. box：（盒）布局的基本单位。
	元素的类型和display属性，决定了这个box的类型。不同类型的box，会参与不同的 Formatting Content (决定如何渲染文档的容器)。因此。box内的元素会以不同的方式渲染。
2. 不同类型的盒子都参与哪些 Formatting Content
> **block-level box(块级盒) **
`display`属性为:` block`、`list-item`、`table`的元素会生成`block-level box`。参与`block formatting content` (块级格式化上下文)

> **inline-level box (行内盒)**
`display`属性为`inline`、`inline-block`、`inline-table`的元素生成`inline-level box`。参与`inline formatting content` (IFC)

3. **Formatting Content**
	`Formatting content`是 W3C CSS2.1 规范中的一个概念。它是页面中的一块渲染区域，并且有一套渲染规则，它决定了其子元素将如何定位，以及和其他元素的关系和相互作用。最常见的`Formatting context`有`Block fomatting context`(简称BFC)和`Inline formatting context`(简称IFC)。

##### 什么是BFC

_BFC：块级格式化上下文（概念）。一个独立的渲染区域，只有块级以及盒子参与，并且规定了内部的块级盒子如何布局，并且和独立区域外部毫不相干。_

BFC规定了内部块级的盒子如何布局，有一套BFC的布局规则。 如下

1. 内部的Box会在垂直方向，一个接一个地放置。
2. Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠
3. 每个元素的margin box的左边，与包含块border box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此。
4. BFC的区域不会与float box重叠。
5. BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素。反之也如此。
6. 计算BFC的高度时，浮动元素也参与计算

##### 如何形成BFC 

1. 根元素或包含根元素的元素
2. 浮动元素（元素的 float 不是 none）
3. 绝对定位元素（元素的 position 为 absolute 或 fixed）
4. display为inline-block, table-cell, table-caption, flex, inline-flex和inline-grid元素的直接子元素
5. overflow 值不为 visible 的块元素

##### BFC的简单用法

直接拿大佬的过来，觉得总结的太精辟了

###### 1. 自适应两栏布局

```css
<style>
    body {
        width: 300px;
        position: relative;
    }
 
    .aside {
        width: 100px;
        height: 150px;
        float: left;
        background: #f66;
    }
 
    .main {
        height: 200px;
        background: #fcc;
    }
</style>
<body>
    <div class="aside"></div>
    <div class="main"></div>
</body>
```

页面

![BFC1](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/5202f8b0-aa95-4234-9971-f0b30870c156)

**应用BFC的规则**
1. 每个元素的`margin box`的左边，与包含块`border box`的左边相接触（对于从左往右的格式，反之相反）。即使存在浮动也是。
此时，`body`元素的内部构成了一个`BFC`
所以，即使`aslide`存在，`main`的左边依旧与包含块的左边相接触。
2. `BFC`的区域不会与`float box`重叠
这时候，我们通过`main`生成`BFC`
```css
.main {
    overflow: hidden;
}
```
这之后，新的BFC不会与浮动的aside 重叠。因此，根据包含块的大小，和aside的宽度类调整自身的宽度。此时main不可设置宽度。

如下：

![BFC2](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/b858bd0b-509e-4599-9b04-8fea14aa1c0f)

###### 2. 清除内部的浮动

```css
<style>
    .par {
        border: 5px solid #fcc;
        width: 300px;
    }
 
    .child {
        border: 5px solid #f66;
        width:100px;
        height: 100px;
        float: left;
    }
</style>
<body>
    <div class="par">
        <div class="child"></div>
        <div class="child"></div>
    </div>
</body>

在这里，应用 计算BFC的高度时，浮动元素也参与计算设置 
.par {
	overflow: hidden;
}
BFC 会被浮动的元素撑开。清除浮动
```

效果图如下：

![BFC3](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/acccebd3-9d09-4451-858d-69cf316af9c4)

![BFC4](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/c41be58b-ff56-4c22-bacb-8f8659c14107)

###### 3. 防止margin 重叠

```css
<style>
    p {
        color: #f55;
        background: #fcc;
        width: 200px;
        line-height: 100px;
        text-align:center;
        margin: 100px;
    }
</style>
<body>
    <p>Haha</p>
    <p>Hehe</p>
</body>
```

![BFC5](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/f4acb658-6aae-44dd-a136-8825706f74a1)

**Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠**

两个P都在body构成的一个BFC中，可以将任意的一个p元素包裹在div标签中，通过div去触发另一个BFC。

```css
<style>
    .wrap {
        overflow: hidden;
    }
</style>
<div class="wrap">
    <p>Haha</p>
</div>
<p>Hehe</p>>
```

![BFC6](https://github.com/askwuxue/askwuxue.github.io/assets/32808762/06126c11-324c-400c-9d61-c60f239581c9)

**总结：**BFC是CSS的精髓所在，只有深刻的理解BFC，然后加以实践，在布局方面在能更加的熟练。菜鸡一枚，继续努力呀。
